services:
  - type: web
    name: text-predictions-api
    runtime: python
    pythonVersion: 3.11.7
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn -w 2 -b 0.0.0.0:$PORT backend.app:app"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
